### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Yard8** [Poruno/Bulma-Navwalker#1]
Simple and concise nav-walker, good work!

Adding the following is-active to public function start_lvl provides better interaction with drop down menus. :)

```
public function start_lvl( &$output, $depth = 0, $args = array() ) {	
	$output .= "<div class='navbar-dropdown is-active'>";
}
```

**Comment by Ripecatfood** [comment]
Thanks for looking into the project! Unfortunately, adding the`is-active` class does nothing since the visibility of the dropdown-menu is controlled via the `.navbar-item` elements' classes which are 
`has-dropdown` and `is-hoverable`.
